---
title: "Assignment 3"
author: "Justine Lang"
date: "2023-03-29"
output: 
  html_document: 
    code_folding: hide
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(ggplot2)
library(tidyverse)
library(PASWR)
library(mra)
library(janitor)
library(here)
```


## Estmated Population Size

### Unburned

***Peromyscus***

```{r}
PM_unburned <- read_csv(here("data", "PM_unburned.csv"))

PM_unburned$X <- NULL

PM_unburned_pa <- PM_unburned %>% 
  select(Encounter1, Encounter2, Encounter3)

PM_unburned_ma <- data.matrix(PM_unburned_pa)
```

```{r}
PMPop_unburned <- F.huggins.estim(capture = ~1, recapture = NULL, PM_unburned_ma)

PMPop_unburned
```

```{r}
# 12.8397, se=1.142
#calculate the SD from the se (se * sqrt(n)) for later use in t-tests comparing means
  1.142*sqrt(12) # = 3.956004 #SD
```


***Neotoma fuscipes***

```{r}
NF_unburned <- read_csv(here("data", "NF_unburned.csv"))

NF_unburned$X <- NULL
```

```{r}
NF_unburned_pa <- NF_unburned %>% 
  select(Encounter1, Encounter2, Encounter3)

NF_unburned_ma <- data.matrix(NF_unburned_pa)
```

```{r}
NFPop_unburned <- F.huggins.estim(capture = ~1, recapture = NULL, NF_unburned_ma)

NFPop_unburned
```

```{r}
### 15.7082 se = 3.3714
3.3714*sqrt(12) ### = 11.67887 #SD
```


***Sceloporus occidentalis***

```{r}
SO_unburned <- read_csv(here("data", "SO_unburned.csv"))

SO_unburned$X <- NULL
```

```{r}
SO_unburned_pa <- SO_unburned %>% 
  select(Encounter1, Encounter2, Encounter3, V4)

SO_unburned_ma <- data.matrix(SO_unburned_pa)
```

```{r}
SOPop_unburned <- F.huggins.estim(capture = ~1, recapture = NULL, SO_unburned_ma)

SOPop_unburned
```

```{r}
### 77.9106 se = 4.6508
4.6508*sqrt(67) ### = 38.06844 #SD
```


### Burned

***Peromyscus***

```{r}
PM_burned <- read_csv(here("data", "PM_burned.csv"))

PM_burned$X <- NULL
```

```{r}
PM_burned_pa <- PM_burned %>% 
  select(Encounter1, Encounter2, Encounter3)

PM_burned_ma <- data.matrix(PM_burned_pa)
```

```{r}
PMPop_burned <- F.huggins.estim(capture = ~1, recapture = NULL, PM_burned_ma)

PMPop_burned
```

```{r}
### 11.5019 se = 1.7525
1.7525*sqrt(10) ### = 5.541892 #SD
```


***Sceloporus occidentalis***

```{r}
SO_burned <- read_csv(here("data", "SO_burned.csv"))

SO_burned$X <- NULL
```

```{r}
SO_burned_pa <- SO_burned %>% 
  select(Encounter1, Encounter2, Encounter3, V4)

SO_burned_ma <- data.matrix(SO_burned_pa)
```

```{r}
SOPop_burned <- F.huggins.estim(capture = ~1, recapture = NULL, SO_burned_ma)

SOPop_burned
```

```{r}
### 73.2445 se = 7.3587
7.3587*sqrt(55) ### = 54.57358 #SD
```


## T-Test Comparision


***Peromyscus***

```{r}
###compare P. maniculatus populations between unburned (x) and burned (y)

PM_ttest <- tsum.test(mean.x=12.8397, s.x=3.956004, n.x=9, mean.y=11.5019, s.y=5.541892, n.y=9, alternative="two.sided", mu=0, var.equal=T, conf.level=0.95)

PM_ttest # No, not significantly different n.x=9, n.y=9: 3 grids trapped for 3 nights each
```


***Neotoma fuscipes***

```{r}
NF_ttest <- tsum.test(mean.x=15.7082, s.x=11.67887, n.x=9, mean.y=0, s.y=0, n.y=9, alternative="two.sided", mu=0, var.equal=T, conf.level=0.95)

NF_ttest ###signficantly different
```


***Sceloporus occidentalis***

```{r}
SO_ttest <- tsum.test(mean.x=77.9106, s.x=4.6508, n.x=12, mean.y=73.2445, s.y=7.3587, n.y=12, alternative="two.sided", mu=0, var.equal=T, conf.level=0.95)

SO_ttest ###not significantly different
```


## Sources of Uncertainty

Text here. 








